export interface BrowserPreset {
  id: string;
  name: string;
  platform: string;
  browser: string;
  version: string;
  category: "Linux" | "macOS" | "Windows" | "Mobile / Tablet" | "Custom / Bot";
  description: string;
  badge?: string;
  recommended?: boolean;
}

export const BROWSER_PRESETS: BrowserPreset[] = [
  {
    id: "ubuntu-chrome",
    name: "Ubuntu Linux · Google Chrome",
    platform: "Ubuntu",
    browser: "Chrome",
    version: "22.04.4",
    category: "Linux",
    description: "Standard Linux desktop signature with high handshake stability.",
    recommended: true,
    badge: "Most Stable",
  },
  {
    id: "macos-safari",
    name: "macOS Sonoma · Apple Safari",
    platform: "macOS",
    browser: "Safari",
    version: "17.4.1",
    category: "macOS",
    description: "Native Apple desktop signature recognized as Safari Web Client.",
    recommended: true,
    badge: "Popular",
  },
  {
    id: "windows-chrome",
    name: "Windows 11 · Google Chrome",
    platform: "Windows",
    browser: "Chrome",
    version: "124.0.6367.91",
    category: "Windows",
    description: "Most common desktop signature for Windows PC users.",
    recommended: true,
    badge: "Official",
  },
  {
    id: "macos-arc",
    name: "macOS · Arc Browser",
    platform: "macOS",
    browser: "Arc",
    version: "1.40.1",
    category: "macOS",
    description: "Modern Chromium-based Arc browser signature.",
  },
  {
    id: "windows-edge",
    name: "Windows 11 · Microsoft Edge",
    platform: "Windows",
    browser: "Edge",
    version: "124.0.2478.67",
    category: "Windows",
    description: "Official Microsoft Edge desktop browser client signature.",
    recommended: true,
  },
  {
    id: "ubuntu-firefox",
    name: "Ubuntu Linux · Mozilla Firefox",
    platform: "Ubuntu",
    browser: "Firefox",
    version: "125.0.2",
    category: "Linux",
    description: "Gecko-based Firefox client for Debian & Ubuntu distributions.",
  },
  {
    id: "windows-operagx",
    name: "Windows 11 · Opera GX Gaming",
    platform: "Windows",
    browser: "Opera GX",
    version: "109.0.5097.79",
    category: "Windows",
    description: "Opera GX dedicated gaming browser signature.",
  },
  {
    id: "arch-brave",
    name: "Arch Linux · Brave Privacy",
    platform: "Arch Linux",
    browser: "Brave",
    version: "1.65.126",
    category: "Linux",
    description: "Privacy-focused Brave browser signature on Arch rolling release.",
  },
  {
    id: "debian-firefox-esr",
    name: "Debian 12 Bookworm · Firefox ESR",
    platform: "Debian",
    browser: "Firefox ESR",
    version: "115.10.0",
    category: "Linux",
    description: "Debian stable enterprise extended-support Firefox build.",
  },
  {
    id: "fedora-chromium",
    name: "Fedora 40 · Chromium Open Source",
    platform: "Fedora",
    browser: "Chromium",
    version: "124.0.6367.91",
    category: "Linux",
    description: "Red Hat Fedora upstream Chromium desktop build.",
  },
  {
    id: "kali-chromium",
    name: "Kali Linux · Security Suite",
    platform: "Kali Linux",
    browser: "Chromium",
    version: "123.0.6312.122",
    category: "Linux",
    description: "Offensive security and penetration testing signature.",
  },
  {
    id: "chromeos-chrome",
    name: "Google ChromeOS · Chromebook",
    platform: "ChromeOS",
    browser: "Chrome",
    version: "123.0.6312.133",
    category: "Mobile / Tablet",
    description: "Official Google Chromebook lightweight web client.",
  },
  {
    id: "android-tablet",
    name: "Android 14 · Chrome Desktop Mode",
    platform: "Android",
    browser: "Chrome Mobile",
    version: "124.0.6367.82",
    category: "Mobile / Tablet",
    description: "Android tablet desktop emulation session.",
  },
  {
    id: "ipados-safari",
    name: "Apple iPadOS 17 · Safari Tablet",
    platform: "iPadOS",
    browser: "Safari",
    version: "17.4.1",
    category: "Mobile / Tablet",
    description: "Apple iPad tablet workstation signature.",
  },
  {
    id: "windows-vivaldi",
    name: "Windows 10 · Vivaldi Power",
    platform: "Windows",
    browser: "Vivaldi",
    version: "6.7.3329.27",
    category: "Windows",
    description: "Power-user customizable Vivaldi browser client.",
  },
  {
    id: "macos-canary",
    name: "macOS Sequoia · Chrome Canary",
    platform: "macOS",
    browser: "Chrome Canary",
    version: "126.0.6439.0",
    category: "macOS",
    description: "Cutting-edge Google Chrome experimental build.",
  },
  {
    id: "freebsd-firefox",
    name: "FreeBSD 14.0 · Firefox Unix",
    platform: "FreeBSD",
    browser: "Firefox",
    version: "124.0.1",
    category: "Linux",
    description: "BSD Unix workstation desktop signature.",
  },
  {
    id: "gentoo-librewolf",
    name: "Gentoo Linux · LibreWolf Hardened",
    platform: "Gentoo",
    browser: "LibreWolf",
    version: "125.0.1",
    category: "Linux",
    description: "Telemetry-free privacy hardened browser signature.",
  },
  {
    id: "windows-server",
    name: "Windows Server 2022 · Headless Host",
    platform: "Windows Server",
    browser: "Chromium",
    version: "124.0.0.0",
    category: "Windows",
    description: "Enterprise cloud server headless signature.",
  },
  {
    id: "nebula-suite",
    name: "Nebula Bot Engine · MultiDevice Core",
    platform: "Nebula Core",
    browser: "Desktop MultiDevice",
    version: "2.4.0",
    category: "Custom / Bot",
    description: "Custom Nebula branded bot client identity.",
    recommended: true,
    badge: "Bot Suite",
  },
  {
    id: "macos-tor",
    name: "macOS · Tor Onion Browser",
    platform: "macOS",
    browser: "Tor Browser",
    version: "13.0.14",
    category: "macOS",
    description: "Onion-routing privacy browser signature.",
  },
  {
    id: "alpine-docker",
    name: "Alpine Linux · Docker Bot Container",
    platform: "Alpine Linux",
    browser: "Baileys Engine",
    version: "20.12.2",
    category: "Custom / Bot",
    description: "Minimal containerized microservice bot identity.",
  },
  {
    id: "macos-desktop-app",
    name: "macOS · WhatsApp Desktop App",
    platform: "macOS",
    browser: "Desktop",
    version: "2.2412.54",
    category: "macOS",
    description: "Electron-based WhatsApp Desktop client mimic.",
  },
  {
    id: "windows-desktop-app",
    name: "Windows · WhatsApp Desktop Native",
    platform: "Windows",
    browser: "Desktop",
    version: "2.2412.54",
    category: "Windows",
    description: "UWP/WinUI native WhatsApp desktop client mimic.",
  },
];
