import express, { NextFunction, Request, Response } from "express";
import path from "path";
import fs from "fs";
import crypto from "crypto";
import QRCode from "qrcode";
import AdmZip from "adm-zip";

import { getConfig, updateConfig } from "./src/bot/config.js";
import { getCommandsDir, getCommands, getCommand } from "./src/bot/commandRegistry.js";
import { getBotState, startLiveBot, stopLiveBot, retryLiveConnection, clearSessionAuth, requestPairingCode, addLog, simulateMessage, clearLogs } from "./src/bot/botEngine.js";

import { getCommandStats } from "./src/bot/commandStats.js";
import { getAIClient, generateTextWithFallback } from "./src/bot/geminiClient.js";
import { savePanelCommand, getPanelCommandSource, exportAllPanelCommands } from "./src/bot/panelCommands.js";
import { replaceAllPanelCommands } from "./src/bot/panelCommands.js";
import { replaceStats as replaceCommandStats } from "./src/bot/commandStats.js";
import { replaceAllPolicies } from "./src/bot/groupAccessStore.js";
import { database } from "./src/bot/database.js";
import { isSafeDownloadUrl } from "./src/bot/urlSafety.js";
import {
  ALLOWED_SECRET_NAMES,
  isAllowedSecretName,
  getSecretStatus,
  setSecret,
  deleteSecret,
  maskSecret,
} from "./src/bot/secrets.js";
import { isAIConfigured as isAIEngineConfigured } from "./src/bot/geminiClient.js";
import { createPanelAuth } from "./src/bot/panelAuth.js";
import { getTempDownload, updateServerBaseUrl, cleanupExpiredZipFiles, getTempStorageStats } from "./src/bot/tempDownloadManager.js";
import { getGroupPolicy, setGroupPolicy, listGroupPolicies } from "./src/bot/groupAccessStore.js";
import { DEFAULT_GROUP_POLICY } from "./src/bot/accessControl.js";
import { getAuditEvents, clearAudit, recordAudit } from "./src/bot/auditTrail.js";
import { getBridgeLoadSummary } from "./src/bot/importedBridge.js";
import { getAIUsageSummary } from "./src/bot/aiQuota.js";
import { loadSubscriptions, saveSubscriptions, sanitizeWatchSubscriptions } from "./src/bot/services/episodeWatchService.js";
import {
  getAllBatchJobs,
  getBatchJob,
  simulateBatchDownload,
  cancelBatchJob,
  retryBatchJob,
  retryEpisode,
  injectSimulatedError
} from "./src/bot/batchDownloadManager.js";

/**
 * Creates the Express application with all /api routes, authentication and
 * rate limiting. The entry point (server.ts) attaches the static/Vite
 * middleware and starts listening — splitting this keeps the API testable.
 */
export function createApp(): express.Express {
  const app = express();
  app.set("trust proxy", true);
  app.use(express.json({ limit: "32mb" }));

  // ---------------------------------------------------------------------------
  // Panel authentication
  // ---------------------------------------------------------------------------
  // PANEL_TOKEN is the admin access key: it is never exposed to the browser.
  // The operator logs in once through /api/auth/login; the server issues a
  // random HttpOnly session cookie. Bearer token remains for API tooling.
  const configuredToken = process.env.PANEL_TOKEN?.trim() || "";
  const panelToken = configuredToken || crypto.randomBytes(24).toString("hex");
  const tokenIsAutoGenerated = !configuredToken;

  // ---------------------------------------------------------------------------
  // Security headers (M13). No X-Frame-Options/frame-ancestors: the panel is
  // intentionally embeddable (host platforms iframe it); the CSP still seals
  // script/style/connect origins. Dev keeps 'unsafe-inline' for Vite's
  // React-refresh preamble.
  // ---------------------------------------------------------------------------
  app.use((_req: Request, res: Response, next: NextFunction) => {
    const isProd = process.env.NODE_ENV === "production";
    res.setHeader("X-Content-Type-Options", "nosniff");
    res.setHeader("Referrer-Policy", "strict-origin-when-cross-origin");
    res.setHeader("Permissions-Policy", "camera=(), microphone=(), geolocation=(), payment=()");
    res.setHeader(
      "Content-Security-Policy",
      [
        "default-src 'self'",
        isProd ? "script-src 'self'" : "script-src 'self' 'unsafe-inline'",
        "style-src 'self' 'unsafe-inline'",
        "img-src 'self' data: blob: https:",
        "media-src 'self' blob: https:",
        "font-src 'self' data:",
        "connect-src 'self' ws: wss:",
        "object-src 'none'",
        "base-uri 'self'",
        "form-action 'self'",
      ].join("; ")
    );
    if (_req.secure || String(_req.headers["x-forwarded-proto"] || "") === "https") {
      res.setHeader("Strict-Transport-Security", "max-age=31536000; includeSubDomains");
    }
    next();
  });

  const panelAuth = createPanelAuth({
    configuredToken: panelToken,
    autoGenerated: tokenIsAutoGenerated,
    appUrl: process.env.APP_URL,
  });

  // M3: Host-header validation. When APP_URL is configured, requests with a
  // Host header that does not match it (or a local/dev proxy address) are
  // rejected before anything is recorded or served. This blocks Host-header
  // poisoning of the absolute temp-download URLs and rebinding-style confusion.
  const allowedHostname = (() => {
    try {
      const u = new URL(process.env.APP_URL || "");
      return u.hostname.toLowerCase();
    } catch {
      return "";
    }
  })();
  app.use((req: Request, res: Response, next: NextFunction) => {
    if (allowedHostname) {
      const hostHeader = req.get("host") || "";
      const hostName = hostHeader.split(":")[0].replace(/^\[|\]$/g, "").toLowerCase();
      // Only the configured public hostname (or loopback for local health
      // checks / reverse proxies that preserve the public Host) is accepted.
      const trusted =
        hostName === allowedHostname || hostName === "localhost" || hostName === "127.0.0.1" || hostName === "::1";
      if (!trusted) {
        console.warn(`[Panel] Rejected request with foreign Host header: "${hostHeader}" (allowed: ${allowedHostname})`);
        return res.status(400).json({ error: "Invalid Host header." });
      }
    }
    next();
  });

  // Record host for generating valid absolute temporary download URLs.
  app.use((req: Request, _res: Response, next: NextFunction) => {
    if (req.headers.host) {
      const protocol = req.headers["x-forwarded-proto"] || req.protocol || "http";
      updateServerBaseUrl(`${protocol}://${req.get("host")}`);
    }
    next();
  });

  // Public health/readiness probe (no secrets, no state mutations).
  app.get("/api/health", (_req, res) => {
    res.json({
      status: "ok",
      uptimeSeconds: Math.floor(process.uptime()),
      pid: process.pid,
      nodeVersion: process.version,
      commands: getCommands().length,
      aiUsage: getAIUsageSummary(),
    });
  });

  // Protect all API routes (except the public media links and the auth
  // endpoints themselves) plus the project archive. The SPA shell, static
  // assets and the login page stay public.
  app.use((req: Request, res: Response, next: NextFunction) => {
    const isApi = req.path.startsWith("/api/");
    const isArchive = req.path === "/nebula-bot-latest.zip";
    if (!isApi && !isArchive) {
      return next();
    }
    if (req.path.startsWith("/api/media/download/") || req.path.startsWith("/d/")) {
      return next();
    }
    if (req.path.startsWith("/api/auth/")) {
      return next();
    }
    panelAuth.requireApiAuth(req, res, next);
  });

  if (tokenIsAutoGenerated) {
    console.log(`🔑 Panel access key (auto-generated): ${panelToken}`);
    console.log("   Use it in the panel login screen, or set PANEL_TOKEN to choose your own.");
  }

  // Sweep expired sessions periodically so the map cannot grow unbounded.
  const sessionSweepTimer = setInterval(() => panelAuth.sweep(), 10 * 60 * 1000);
  sessionSweepTimer.unref();


  // ---------------------------------------------------------------------------
  // Rate limiting (in-memory fixed window with memory safety ceiling)
  // ---------------------------------------------------------------------------
  const MAX_RATE_LIMIT_KEYS = 5000;
  const buckets = new Map<string, { count: number; resetAt: number }>();

  function rateLimit(max: number, windowMs: number) {
    return (req: Request, res: Response, next: NextFunction) => {
      // Key on the socket peer address (not req.ip): with `trust proxy`,
      // req.ip trusts the client-supplied X-Forwarded-For chain, which lets
      // a direct caller rotate identities and bypass the limiter.
      const peer = req.socket.remoteAddress || "unknown";
      const key = `${req.path}|${peer}`;
      const now = Date.now();
      const bucket = buckets.get(key);
      if (!bucket || bucket.resetAt < now) {
        if (buckets.size >= MAX_RATE_LIMIT_KEYS) {
          // Prune expired buckets first
          for (const [k, b] of buckets) {
            if (b.resetAt < now) buckets.delete(k);
          }
          // If still over capacity, drop oldest entries to prevent memory exhaustion
          if (buckets.size >= MAX_RATE_LIMIT_KEYS) {
            let pruned = 0;
            for (const k of buckets.keys()) {
              buckets.delete(k);
              if (++pruned > 200) break;
            }
          }
        }
        buckets.set(key, { count: 1, resetAt: now + windowMs });
        return next();
      }
      bucket.count++;
      if (bucket.count > max) {
        return res.status(429).json({ error: "Too many requests. Please slow down and try again shortly." });
      }
      next();
    };
  }

  const generalLimiter = rateLimit(300, 60_000);
  app.use("/api", generalLimiter);

  // Stricter limits for expensive / abuse-prone routes
  app.post("/api/auth/login", rateLimit(8, 60_000));
  app.post("/api/bot/simulate", rateLimit(30, 60_000));
  app.post("/api/bot/commands/save", rateLimit(10, 60_000));
  app.post("/api/bot/commands/generate", rateLimit(10, 60_000));
  app.get("/api/bot/download-zip", rateLimit(5, 60_000));
  app.post("/api/gemini/transcribe", rateLimit(10, 60_000));
  app.post("/api/gemini/voice-conversation", rateLimit(10, 60_000));
  app.post("/api/bot/secrets", rateLimit(10, 60_000));
  app.get("/api/bot/access", rateLimit(30, 60_000));
  app.post("/api/bot/access/:groupJid", rateLimit(20, 60_000));
  app.delete("/api/bot/secrets", rateLimit(10, 60_000));

  // Periodically drop expired buckets so the map cannot grow unbounded.
  const sweepTimer = setInterval(() => {
    const now = Date.now();
    for (const [key, bucket] of buckets) {
      if (bucket.resetAt < now) buckets.delete(key);
    }
  }, 10 * 60 * 1000);
  sweepTimer.unref();

  // ---------------------------------------------------------------------------
  // Configuration helpers
  // ---------------------------------------------------------------------------
  function sanitizeConfig(input: any): Partial<any> {
    const out: any = {};
    if (typeof input?.botName === "string") {
      const name = input.botName.trim().slice(0, 40);
      if (name) out.botName = name;
    }
    if (typeof input?.prefix === "string") {
      const prefix = input.prefix.trim();
      if (!prefix || prefix.length > 2) {
        throw new Error("Prefix must be 1-2 characters long.");
      }
      out.prefix = prefix;
    }
    if (typeof input?.ownerNumber === "string") {
      out.ownerNumber = input.ownerNumber.replace(/[^0-9+]/g, "").slice(0, 16);
    }
    if (typeof input?.botImage === "string" && /^https?:\/\//.test(input.botImage)) {
      out.botImage = input.botImage.slice(0, 500);
    }
    if (typeof input?.newsletterUrl === "string" && /^https?:\/\//.test(input.newsletterUrl)) {
      out.newsletterUrl = input.newsletterUrl.slice(0, 500);
    }
    if (typeof input?.newsletterName === "string") {
      const name = input.newsletterName.trim().slice(0, 60);
      if (name) out.newsletterName = name;
    }
    if (typeof input?.browserPlatform === "string") {
      const p = input.browserPlatform.trim().slice(0, 50);
      if (p) out.browserPlatform = p;
    }
    if (typeof input?.browserName === "string") {
      const b = input.browserName.trim().slice(0, 50);
      if (b) out.browserName = b;
    }
    if (typeof input?.browserVersion === "string") {
      const v = input.browserVersion.trim().slice(0, 40);
      if (v) out.browserVersion = v;
    }
    return out;
  }

  // ---------------------------------------------------------------------------
  // API: Panel session management (login / logout / status)
  // ---------------------------------------------------------------------------
  // Explicitly retired: the old /auth/token endpoint leaked the panel key.
  // Return 404 instead of letting the SPA fallback answer with the shell.
  app.get("/auth/token", (_req, res) => {
    res.status(404).json({ error: "Not found." });
  });

  app.post("/api/auth/login", (req, res) => {
    const { token } = req.body ?? {};
    const result = panelAuth.login(token);
    if (!result.success || !result.sessionId) {
      return res.status(401).json({ error: result.error || "Login failed." });
    }
    panelAuth.setCookie(res, result.sessionId);
    res.json({ success: true });
  });

  app.post("/api/auth/logout", (req, res) => {
    panelAuth.logout(req, res);
    res.json({ success: true });
  });

  app.get("/api/auth/me", (req, res) => {
    res.json({ authenticated: panelAuth.isAuthenticated(req) });
  });

  // ---------------------------------------------------------------------------
  // API: Get and Update Configuration
  // ---------------------------------------------------------------------------
  app.get("/api/bot/config", (req, res) => {
    const cfg: any = { ...getConfig() };
    delete cfg.sessionString;
    res.json(cfg);
  });

  app.post("/api/bot/config", (req, res) => {
    try {
      const updated = updateConfig(sanitizeConfig(req.body));
      addLog(`⚙️ Configuration updated from panel: Bot Name: "${updated.botName}", Prefix: "${updated.prefix}"`);
      res.json(updated);
    } catch (error: any) {
      res.status(400).json({ error: error?.message || "Invalid configuration." });
    }
  });

  // ---------------------------------------------------------------------------
  // API: Secrets management (masked — raw values never leave the server)
  // ---------------------------------------------------------------------------
  app.get("/api/bot/secrets", (req, res) => {
    res.json({ secrets: ALLOWED_SECRET_NAMES.map((name) => getSecretStatus(name)) });
  });

  app.post("/api/bot/secrets", (req, res) => {
    const { name, value } = req.body ?? {};
    if (typeof name !== "string" || !isAllowedSecretName(name)) {
      return res.status(400).json({ error: "Unsupported secret name." });
    }
    if (typeof value !== "string" || !value.trim()) {
      return res.status(400).json({ error: "Secret value is required." });
    }
    const clean = value.trim();
    if (clean.length > 2000) {
      return res.status(400).json({ error: "Secret value is too long (max 2000 characters)." });
    }
    if (/[\r\n]/.test(clean)) {
      return res.status(400).json({ error: "Secret value must be a single line." });
    }
    if (clean === "MY_GEMINI_API_KEY" || clean === "YOUR_API_KEY_HERE") {
      return res.status(400).json({ error: "That looks like the placeholder value — please paste your real key." });
    }

    const result = setSecret(name, clean);
    addLog(`🔑 Secret "${name}" updated (${maskSecret(clean)}).`);
    res.json({ success: true, name, masked: maskSecret(clean), ...result });
  });

  app.delete("/api/bot/secrets", (req, res) => {
    const { name } = req.body ?? {};
    if (typeof name !== "string" || !isAllowedSecretName(name)) {
      return res.status(400).json({ error: "Unsupported secret name." });
    }
    const result = deleteSecret(name);
    addLog(`🔑 Secret "${name}" removed.`);
    res.json({ success: true, name, ...result });
  });

  // ---------------------------------------------------------------------------
  // API: Download the full project source as a ZIP (for backups/moving).
  // Auth is enforced by the global middleware above; the SPA fetches it with
  // the session cookie, so it still works inside the preview proxy.
  // ---------------------------------------------------------------------------
  app.get("/nebula-bot-latest.zip", (req, res) => {
    const zipPath = path.join(process.cwd(), "nebula-bot-latest.zip");
    if (!fs.existsSync(zipPath)) {
      return res.status(404).json({ error: "Project archive not available on this deployment." });
    }
    res.download(zipPath, "nebula-bot-latest.zip");
  });

  // ---------------------------------------------------------------------------
  // API: Get Connection State & QR Code
  // ---------------------------------------------------------------------------
  app.get("/api/bot/status", (req, res) => {
    res.json(getBotState());
  });

  app.get("/api/bot/qr", async (req, res) => {
    const { qrCode } = getBotState();
    if (!qrCode) {
      return res.status(404).json({ error: "No active QR code. Start the live connection first." });
    }
    try {
      const qrUrl = await QRCode.toDataURL(qrCode, { margin: 2, width: 250 });
      res.json({ qrUrl });
    } catch (error: any) {
      res.status(500).json({ error: "Failed to generate QR code image." });
    }
  });

  // ---------------------------------------------------------------------------
  // API: Start / Stop Live Bot
  // ---------------------------------------------------------------------------
  app.post("/api/bot/start", (req, res) => {
    startLiveBot(true);
    res.json({ success: true, message: "Live bot start triggered." });
  });

  app.post("/api/bot/pair-code", async (req, res) => {
    const { phoneNumber } = req.body;
    if (typeof phoneNumber !== "string" || !phoneNumber.trim()) {
      return res.status(400).json({ error: "Please provide a valid WhatsApp phone number with country code (e.g. 1234567890 or 628123456789)." });
    }

    try {
      const result = await requestPairingCode(phoneNumber);
      if (!result.success) {
        return res.status(400).json({ error: result.error || "Failed to generate pairing code." });
      }
      res.json({
        success: true,
        code: result.code,
        expiresAt: result.expiresAt,
        message: "Pairing code generated successfully. Enter this code in WhatsApp -> Linked Devices -> Link with phone number instead."
      });
    } catch (error: any) {
      console.error("Pairing code error:", error);
      res.status(500).json({ error: error.message || "Internal server error generating pairing code." });
    }
  });

  app.post("/api/bot/stop", (req, res) => {
    stopLiveBot();
    res.json({ success: true, message: "Live bot stop triggered." });
  });

  app.post("/api/bot/clear-auth", async (req, res) => {
    try {
      const result = await clearSessionAuth();
      if (!result.success) {
        return res.status(500).json({
          success: false,
          error: result.error || "Failed to clear session authentication cache.",
          filesRemoved: result.filesRemoved,
          authDir: result.authDir,
        });
      }
      res.json({
        success: true,
        filesRemoved: result.filesRemoved,
        authDir: result.authDir,
        message: result.message,
      });
    } catch (error: any) {
      console.error("Failed to clear auth cache:", error);
      const errorMsg = error?.message || String(error);
      addLog(`❌ Server Error in /api/bot/clear-auth: ${errorMsg}`);
      res.status(500).json({ success: false, error: errorMsg });
    }
  });

  app.post("/api/bot/retry", async (req, res) => {
    try {
      const result = await retryLiveConnection();
      if (!result.success) {
        return res.status(500).json({
          success: false,
          error: result.error || "Failed to reset session and restart connection.",
          filesRemoved: result.filesRemoved,
          authDir: result.authDir,
        });
      }
      res.json({
        success: true,
        filesRemoved: result.filesRemoved,
        authDir: result.authDir,
        message: result.message,
      });
    } catch (error: any) {
      console.error("Failed to retry connection:", error);
      const errorMsg = error?.message || String(error);
      addLog(`❌ Server Error in /api/bot/retry: ${errorMsg}`);
      res.status(500).json({ success: false, error: errorMsg });
    }
  });


  // ---------------------------------------------------------------------------
  // API: Clear Logs
  // ---------------------------------------------------------------------------
  app.post("/api/bot/clear-logs", (req, res) => {
    clearLogs();
    res.json({ success: true });
  });

  // ---------------------------------------------------------------------------
  // API: Command Simulation Playground
  // ---------------------------------------------------------------------------
  app.post("/api/bot/simulate", async (req, res) => {
    const { senderName, text } = req.body;
    if (typeof text !== "string" || !text.trim()) {
      return res.status(400).json({ error: "Message text is required." });
    }
    if (text.length > 2000) {
      return res.status(400).json({ error: "Message text is too long (max 2000 characters)." });
    }
    const cleanSenderName = typeof senderName === "string" ? senderName.trim().slice(0, 40) : "Guest User";
    const result = await simulateMessage(cleanSenderName || "Guest User", text);
    res.json(result);
  });

  // ---------------------------------------------------------------------------
  // API: List Commands (deduplicated by the registry)
  // ---------------------------------------------------------------------------
  app.get("/api/bot/commands", (req, res) => {
    const commands = getCommands().map(cmd => ({
      name: cmd.name,
      category: cmd.category,
      description: cmd.description,
      usage: cmd.usage || cmd.name,
      aliases: cmd.aliases || [],
    }));
    res.json(commands);
  });

  // ---------------------------------------------------------------------------
  // API: RoleGuard — group access policies (panel ACL)
  // ---------------------------------------------------------------------------
  app.get("/api/bot/access", (_req, res) => {
    res.json({
      policies: listGroupPolicies(),
      defaults: DEFAULT_GROUP_POLICY,
      commandIndex: getCommands().map((cmd) => ({ name: cmd.name, category: cmd.category })),
    });
  });

  app.get("/api/bot/access/:groupJid", (req, res) => {
    res.json({ groupJid: req.params.groupJid, policy: getGroupPolicy(req.params.groupJid) });
  });

  app.post("/api/bot/access/:groupJid", (req, res) => {
    try {
      const body = req.body || {};
      const policy = setGroupPolicy(req.params.groupJid, {
        defaultTo: body.defaultTo === "deny" || body.defaultTo === "allow" ? body.defaultTo : undefined,
        memberDeny: body.memberDeny,
        memberAllow: body.memberAllow,
        adminAllow: body.adminAllow,
      });
      addLog(`🛡️ RoleGuard policy updated for ${req.params.groupJid}`);
      res.json({ groupJid: req.params.groupJid, policy });
    } catch (error: any) {
      res.status(400).json({ error: error?.message || "Invalid policy." });
    }
  });

  // ---------------------------------------------------------------------------
  // API: Security audit trail (bounded ring, append-only to server)
  // ---------------------------------------------------------------------------
  app.get("/api/bot/audit", rateLimit(30, 60_000), (req, res) => {
    const limit = Math.min(parseInt(String(req.query.limit || "100"), 10) || 100, 500);
    res.json({ events: getAuditEvents(limit) });
  });

  app.delete("/api/bot/audit", rateLimit(5, 60_000), (req, res) => {
    clearAudit();
    recordAudit("panel", "audit.clear", "panel", "Audit trail cleared by operator");
    addLog("🧹 Audit trail cleared from panel.");
    res.json({ success: true });
  });

  // ---------------------------------------------------------------------------
  // API: Backup / restore (config sanitized, no secrets, no session material)
  // ---------------------------------------------------------------------------
  app.get("/api/bot/backup", rateLimit(5, 60_000), (req, res) => {
    const cfg: any = { ...getConfig() };
    delete cfg.sessionString;
    res.json({
      format: "nebula-backup@1",
      exportedAt: new Date().toISOString(),
      config: cfg,
      aiUsage: getAIUsageSummary(),
      // B1 fix (2026-09-01): the export used to omit every section the
      // restore could apply — backups were near-useless. Now lossless for:
      groups: database.getAllGroups(),
      warnings: database.getAllWarnings(),
      stats: getCommandStats(),
      accessPolicies: listGroupPolicies(),
      panelCommands: exportAllPanelCommands(),
      watchSubscriptions: loadSubscriptions()
    });
  });

  app.post("/api/bot/backup/restore", rateLimit(5, 60_000), (req, res) => {
    try {
      const body = req.body || {};
      if (body.format !== "nebula-backup@1" || typeof body !== "object") {
        return res.status(400).json({ error: "Unsupported backup format." });
      }
      const applied: string[] = [];

      if (body.config && typeof body.config === "object") {
        const cfg: any = { ...body.config };
        delete cfg.sessionString;
        updateConfig(sanitizeConfig(cfg));
        applied.push("config");
      }
      if (body.groups && typeof body.groups === "object" && Object.keys(body.groups).length <= 5000) {
        applied.push(`groups:${database.replaceAllGroups(body.groups)}`);
      }
      if (body.warnings && typeof body.warnings === "object" && Object.keys(body.warnings).length <= 2000) {
        applied.push(`warnings:${database.replaceAllWarnings(body.warnings)}`);
      }
      if (body.stats && typeof body.stats === "object") {
        applied.push(`stats:${replaceCommandStats(body.stats)}`);
      }
      if (body.accessPolicies && typeof body.accessPolicies === "object") {
        applied.push(`policies:${replaceAllPolicies(body.accessPolicies)}`);
      }
      if (Array.isArray(body.watchSubscriptions)) {
        const clean = sanitizeWatchSubscriptions(body.watchSubscriptions);
        saveSubscriptions(clean);
        applied.push(`watch:${clean.length}`);
      }
      if (Array.isArray(body.panelCommands)) {
        const result = replaceAllPanelCommands(body.panelCommands);
        applied.push(`commands:${result.count}`);
        if (result.errors.length > 0) {
          console.warn(`[Backup] Some panel commands skipped during restore:`, result.errors);
        }
      }
      recordAudit("panel", "backup.restore", "panel", `Applied: ${applied.join(", ")}`);
      addLog(`♻️ Backup restored from panel: ${applied.join(", ")}`);
      res.json({ success: true, applied });
    } catch (error: any) {
      res.status(400).json({ error: error?.message || "Invalid backup payload." });
    }
  });

  // ---------------------------------------------------------------------------
  // API: Get command usage analytics
  // ---------------------------------------------------------------------------
  app.get("/api/bot/analytics", (req, res) => {
    res.json({ stats: getCommandStats(), aiUsage: getAIUsageSummary() });
  });

  // ---------------------------------------------------------------------------
  // API: Full Commands & Backend Checkup Diagnostic Suite
  // ---------------------------------------------------------------------------
  app.get("/api/bot/checkup", rateLimit(5, 60_000), async (req, res) => {
    const startTime = Date.now();
    const tests: any[] = [];
    const memory = process.memoryUsage();

    // 1. Registry & Command Integrity Check
    const commandsList = getCommands();
    const categoryCounts: Record<string, number> = {};
    let totalAliases = 0;
    let malformedCommands = 0;

    for (const cmd of commandsList) {
      const cat = cmd.category || "General";
      categoryCounts[cat] = (categoryCounts[cat] || 0) + 1;
      if (cmd.aliases && Array.isArray(cmd.aliases)) {
        totalAliases += cmd.aliases.length;
      }
      if (!cmd.name || typeof cmd.execute !== "function") {
        malformedCommands++;
      }
    }

    const bridge = getBridgeLoadSummary();
    tests.push({
      name: "Vendored Command Bridge",
      category: "registry",
      status: bridge.skipped === 0 ? "pass" : "warn",
      latencyMs: 1,
      message:
        bridge.skipped === 0
          ? `${bridge.loaded} imported commands loaded; no missing native dependencies.`
          : `${bridge.skipped} vendored commands skipped (missing native dependencies / load errors). This is expected if whatsapp-rust-bridge is not installed — the menu omits them.`,
      details: { loaded: bridge.loaded, skipped: bridge.skipped, skippedFiles: bridge.skippedFiles.slice(0, 12) },
    });

    tests.push({
      name: "Command Registry Validation",
      category: "registry",
      status: malformedCommands === 0 && commandsList.length > 0 ? "pass" : "fail",
      latencyMs: 1,
      message: `${commandsList.length} unique commands registered across ${Object.keys(categoryCounts).length} categories (${totalAliases} aliases).`,
      details: {
        totalCommands: commandsList.length,
        categories: categoryCounts,
        aliases: totalAliases,
        malformed: malformedCommands
      }
    });

    // 2. Storage & Database Integrity Check
    const dbStart = Date.now();
    try {
      const testGroupId = "diagnostic_healthcheck@g.us";
      const initialSettings = database.getGroupSettings(testGroupId);
      database.updateGroupSettings(testGroupId, { antilink: true });
      const readBack = database.getGroupSettings(testGroupId);
      const isDbOk = readBack.antilink === true;

      // Revert test write
      database.updateGroupSettings(testGroupId, initialSettings);

      tests.push({
        name: "Atomic Storage & Database",
        category: "storage",
        status: isDbOk ? "pass" : "fail",
        latencyMs: Date.now() - dbStart,
        message: "JSON atomic database read/write and memory cache operating normally.",
        details: { testGroup: testGroupId, verified: isDbOk }
      });
    } catch (dbErr: any) {
      tests.push({
        name: "Atomic Storage & Database",
        category: "storage",
        status: "fail",
        latencyMs: Date.now() - dbStart,
        message: `Database check error: ${dbErr?.message || dbErr}`
      });
    }

    // 3. Dependency & Codec Verification
    const depsToCheck = [
      { name: "@whiskeysockets/baileys", label: "WhatsApp Multi-Device Engine" },
      { name: "@google/genai", label: "Gemini AI Official SDK" },
      { name: "fluent-ffmpeg", label: "FFmpeg Audio/Video Converter" },
      { name: "node-webpmux", label: "WebP / Sticker Codec Tools" },
      { name: "mumaker", label: "Textmaker Graphics Generator" },
      { name: "@bochilteam/scraper", label: "Entertainment & Media Scrapers" },
      { name: "@vitalets/google-translate-api", label: "Google Multi-Language Translate" },
      { name: "qrcode", label: "WhatsApp QR Image Engine" },
      { name: "adm-zip", label: "Project Archive & Deployment Packager" },
      { name: "ytdl-core", label: "YouTube Stream Downloader" },
      { name: "ruhend-scraper", label: "Extended Media Scraper Engine" },
      { name: "whatsapp-rust-bridge", label: "Native WhatsApp Rust Bridge (imported commands)" },
    ];

    const depResults = depsToCheck.map(dep => {
      let available = false;
      try {
        require.resolve(dep.name);
        available = true;
      } catch (e) {
        available = false;
      }
      return {
        name: dep.name,
        label: dep.label,
        available
      };
    });

    const missingCriticalDeps = depResults.filter(d => !d.available);
    tests.push({
      name: "Native Codecs & Dependencies",
      category: "dependencies",
      status: missingCriticalDeps.length === 0 ? "pass" : missingCriticalDeps.length < 3 ? "warn" : "fail",
      latencyMs: 2,
      message: `${depResults.filter(d => d.available).length}/${depResults.length} required libraries and binary codecs loaded.`,
      details: depResults
    });

    // 4. Security Sandbox & SSRF Protection Check
    const secStart = Date.now();
    try {
      const safeTest = await isSafeDownloadUrl("https://example.com/test.mp4");
      const unsafeLocalhost = await isSafeDownloadUrl("http://localhost:3000/api");
      const unsafeIp = await isSafeDownloadUrl("http://127.0.0.1:8080");
      const isSecOk = safeTest === true && unsafeLocalhost === false && unsafeIp === false;

      tests.push({
        name: "SSRF Sandbox & Guardrails",
        category: "security",
        status: isSecOk ? "pass" : "fail",
        latencyMs: Date.now() - secStart,
        message: "SSRF protection blocks private loopbacks, localhost & non-routable IPs.",
        details: { safeAllowed: safeTest, localhostBlocked: !unsafeLocalhost, loopbackBlocked: !unsafeIp }
      });
    } catch (secErr: any) {
      tests.push({
        name: "SSRF Sandbox & Guardrails",
        category: "security",
        status: "warn",
        latencyMs: Date.now() - secStart,
        message: `Security sandbox check: ${secErr?.message || secErr}`
      });
    }

    // 5. AI Engine Subsystem (Gemini primary, NVIDIA NIM fallback — 8.35)
    const isAiConfigured = isAIEngineConfigured();
    tests.push({
      name: "Gemini AI Engine Subsystem",
      category: "ai",
      status: isAiConfigured ? "pass" : "warn",
      latencyMs: 1,
      message: isAiConfigured
        ? "Gemini API key configured with automatic multi-model fallback chain."
        : "Gemini API key not configured yet; AI commands will prompt for configuration in Secrets.",
      details: {
        configured: isAiConfigured,
        fallbackModels: ["gemini-3.7-flash", "gemini-3.5-flash", "gemini-3.1-flash-lite"]
      }
    });

    // 6. Synthetic Command Simulation Verification Suite
    const sampleCommandsToTest = [
      // Network-dependent probes are opt-in (NEBULA_CHECKUP_NETWORK=1) so the
      // diagnostic suite is cheap and offline-safe by default.
      ...(String(process.env.NEBULA_CHECKUP_NETWORK || "0") === "1"
        ? [{ text: ".weather London", expected: "Weather", name: "Weather API Integration" }]
        : []),
      { text: ".ping", expected: "Status", name: "Core Ping Command" },
      { text: ".menu", expected: "SERVICES", name: "Dynamic Menu Command" },
      { text: ".help ping", expected: "ping", name: "Help System" },
      { text: ".calc (25 * 4) + 50", expected: "150", name: "Calculator Engine" },
      { text: ".joke", expected: "", name: "Entertainment Joke Command" },
      { text: ".quote", expected: "", name: "Quote Generator" },
      { text: ".dare", expected: "", name: "Dare Generator" },
      { text: ".roast me", expected: "Roast", name: "Roast Engine" },
      { text: ".antilink get", expected: "Antilink", name: "Antilink Protection" },
      { text: ".antibot status", expected: "Antibot", name: "Antibot System" },
      { text: ".antitag get", expected: "Antitag", name: "Antitag Protection" }
    ];

    for (const item of sampleCommandsToTest) {
      const simStart = Date.now();
      try {
        const simResult = await simulateMessage("System Auditor", item.text);
        const latency = Date.now() - simStart;
        const pass = !item.expected || (simResult.text && simResult.text.toLowerCase().includes(item.expected.toLowerCase()));
        tests.push({
          name: item.name,
          category: "simulation",
          status: pass ? "pass" : "warn",
          latencyMs: latency,
          message: simResult.text ? simResult.text.slice(0, 120).replace(/\n/g, " ") : "Execution finished with status OK",
          details: { command: item.text, output: simResult.text, emoji: simResult.emoji }
        });
      } catch (simErr: any) {
        tests.push({
          name: item.name,
          category: "simulation",
          status: "fail",
          latencyMs: Date.now() - simStart,
          message: `Simulation error: ${simErr?.message || simErr}`
        });
      }
    }

    // Calculate overall health score
    const totalTests = tests.length;
    const passedTests = tests.filter(t => t.status === "pass").length;
    const warnTests = tests.filter(t => t.status === "warn").length;
    const healthScore = Math.round(((passedTests + (warnTests * 0.7)) / totalTests) * 100);

    const overallStatus = healthScore >= 90 ? "healthy" : healthScore >= 70 ? "warning" : "degraded";
    const durationMs = Date.now() - startTime;

    addLog(`🔍 [Diagnostic Checkup] Completed full checkup in ${durationMs}ms: Score ${healthScore}% (${overallStatus.toUpperCase()})`);

    res.json({
      timestamp: new Date().toISOString(),
      overallStatus,
      healthScore,
      durationMs,
      system: {
        nodeVersion: process.version,
        platform: process.platform,
        uptimeSeconds: Math.floor(process.uptime()),
        memory: {
          heapUsedMB: Math.round(memory.heapUsed / (1024 * 1024)),
          heapTotalMB: Math.round(memory.heapTotal / (1024 * 1024)),
          rssMB: Math.round(memory.rss / (1024 * 1024)),
        },
        pid: process.pid,
      },
      commands: {
        totalRegistered: commandsList.length,
        byCategory: categoryCounts,
        uniqueNamesCount: commandsList.length,
        aliasesCount: totalAliases,
      },
      tests,
      dependencies: depResults,
    });
  });

  // ---------------------------------------------------------------------------
  // API: Get details or code of a single command
  // ---------------------------------------------------------------------------
  app.get("/api/bot/commands/:name", (req, res) => {
    const cmdName = req.params.name.toLowerCase();
    const cmd = getCommand(cmdName);
    if (!cmd) {
      return res.status(404).json({ error: "Command not found." });
    }

    // Panel-authored commands live in the data store; built-ins on disk.
    let code = getPanelCommandSource(cmdName) || "";

    if (!code) {
      const filePath = path.join(getCommandsDir(), `${cmdName}.ts`);
      if (fs.existsSync(filePath)) {
        code = fs.readFileSync(filePath, "utf-8");
      } else {
      // Return structured representation if file not on disk
        code = `import { BotCommand } from "../types.js";\n\n// Autogenerated dynamic code fallback\nconst cmd: BotCommand = {\n  name: "${cmd.name}",\n  category: "${cmd.category}",\n  description: "${cmd.description}",\n  execute: async (sock, msg, context) => {\n    await context.reply("Hello from ${cmd.name}!");\n  }\n};\nexport default cmd;`;
      }
    }

    res.json({
      ...cmd,
      code
    });
  });

  // ---------------------------------------------------------------------------
  // API: Save or Create a command file
  // ---------------------------------------------------------------------------
  app.post("/api/bot/commands/save", async (req, res) => {
    const { name, code } = req.body;
    if (typeof name !== "string" || typeof code !== "string" || !code.trim()) {
      return res.status(400).json({ error: "Name and code are required." });
    }
    if (code.length > 100_000) {
      return res.status(400).json({ error: "Command code is too large (max 100KB)." });
    }

    const cleanName = name.trim().toLowerCase().replace(/[^a-z0-9]/g, "");
    if (!cleanName) {
      return res.status(400).json({ error: "Invalid command name: use letters and digits only." });
    }

    // C4: panel commands are stored as data and executed in the capability-
    // limited sandbox (panelCommandSandbox.ts). They are never written into
    // the source tree nor compiled into loadable modules.
    const category = (typeof req.body.category === "string" && req.body.category.trim() ? req.body.category.trim() : "Utility").slice(0, 40);
    const description = (typeof req.body.description === "string" ? req.body.description.trim() : `Panel command ${cleanName}`).slice(0, 200);
    const usage = typeof req.body.usage === "string" ? req.body.usage.trim().slice(0, 120) : `.${cleanName}`;
    const aliases = Array.isArray(req.body.aliases) ? req.body.aliases.map((a: any) => String(a).trim().slice(0, 32)).filter(Boolean) : [];

    try {
      const result = savePanelCommand({
        name: cleanName,
        category,
        description,
        usage,
        aliases,
        source: code,
      });
      if (!result.ok) {
        addLog(`🛡️ [PanelCommands] Rejected save of "${cleanName}": ${result.error}`);
        return res.status(400).json({ success: false, error: result.error, message: result.message });
      }
      addLog(`📝 Saved panel command (sandboxed): ${cleanName}`);
      res.json({ success: true, message: result.message, loaded: result.loaded });
    } catch (error: any) {
      res.status(500).json({ error: `Failed to save command: ${error.message}` });
    }
  });

  // ---------------------------------------------------------------------------
  // API: AI-Powered Command Builder (using Gemini)
  // ---------------------------------------------------------------------------
  app.post("/api/bot/commands/generate", async (req, res) => {
    const { prompt, commandName, category, description } = req.body;

    if (typeof prompt !== "string" || !prompt.trim() || typeof commandName !== "string" || !commandName.trim()) {
      return res.status(400).json({ error: "Prompt and commandName are required." });
    }
    if (prompt.length > 4000) {
      return res.status(400).json({ error: "Prompt is too long (max 4000 characters)." });
    }

    // Security Guardrail: Prevent prompt injection or generation of unsafe server execution APIs
    const lowerPrompt = prompt.toLowerCase();
    const maliciousPatterns = [
      "ignore previous instructions",
      "ignore the instructions",
      "ignore original guidelines",
      "system commands",
      "child_process",
      "exec(",
      "execsync",
      "spawn(",
      "fs.unlink",
      "fs.rmdir",
      "rm -rf"
    ];
    const isSuspicious = maliciousPatterns.some(pattern => lowerPrompt.includes(pattern));
    if (isSuspicious) {
      addLog(`🛡️ [Guardrail] Blocked suspicious generation prompt targeting "${commandName}": Injection or unsafe system patterns detected.`);
      return res.status(400).json({ error: "Security Guardrail: Prompt contains content that violates safe dynamic generation guidelines." });
    }

    if (!isAIEngineConfigured()) {
      return res.status(400).json({ error: "No AI engine configured. Please add GEMINI_API_KEY or NVIDIA_NIM_API_KEY to Settings > Secrets." });
    }

    const cleanName = commandName.trim().toLowerCase().replace(/[^a-z0-9]/g, "");
    if (!cleanName) {
      return res.status(400).json({ error: "Invalid command name: use letters and digits only." });
    }
    const cleanCategory = (typeof category === "string" ? category : "Utility").trim().slice(0, 40);
    const cleanDesc = (typeof description === "string" ? description : `Dynamic AI-generated command for ${cleanName}`).trim().slice(0, 200);

    addLog(`🤖 Asking Gemini to design command: "${cleanName}" (${prompt})`);

    try {
      const aiPrompt = `
Generate a fully functional TypeScript WhatsApp command file for a Baileys bot.
The file must export a default object implementing the following interface:

interface BotCommand {
  name: string;
  category: string;
  description: string;
  usage?: string;
  execute: (sock: any, msg: any, context: {
    sender: string;
    senderName: string;
    isOwner: boolean;
    isAdmin: boolean;
    prefix: string;
    commandName: string;
    args: string[];
    fullMessage: string;
    reply: (text: string, mediaUrl?: string) => Promise<any>;
    react: (emoji: string) => Promise<any>;
    downloadMedia?: () => Promise<Buffer | null>;
  }) => Promise<void> | void;
}

The command name is: "${cleanName}"
The category is: "${cleanCategory}"
The description is: "${cleanDesc}"
Specific instructions for what the command should do: "${prompt}"

Make the logic clean, fully typed, and robust. Always use markdown formatting in text outputs for neat messaging layout (e.g. bold like *text*, italics like _text_). If you use external API fetches, handle errors cleanly with try-catch and output helpful error messages. Use standard ES Module imports, specifically relative importing of the BotCommand type if needed, e.g. import { BotCommand } from "../types.js";

IMPORTANT: Output ONLY the raw TypeScript code. No markdown wrapping (like \`\`\`typescript ... \`\`\`), no conversational intros. Just raw TS code so I can save it directly to a file.
`;

      const codeRaw = await generateTextWithFallback(aiPrompt, undefined, "gemini-3.7-flash");
      let code = codeRaw || "";

      // Safety: strip markdown wraps if Gemini returned them despite instructions
      if (code.includes("```typescript")) {
        code = code.split("```typescript")[1].split("```")[0];
      } else if (code.includes("```ts")) {
        code = code.split("```ts")[1].split("```")[0];
      } else if (code.includes("```")) {
        code = code.split("```")[1].split("```")[0];
      }

      code = code.trim();

      // Save through the sandboxed panel-command store (C4): no source-tree
      // write, no compile-to-executable, no dynamic import.
      const result = savePanelCommand({
        name: cleanName,
        category: cleanCategory,
        description: cleanDesc,
        usage: `.${cleanName}`,
        aliases: [],
        source: code,
      });
      if (!result.ok) {
        addLog(`🛡️ [PanelCommands] Rejected AI-generated command "${cleanName}": ${result.error}`);
        return res.status(400).json({ success: false, error: result.error, message: result.message });
      }

      addLog(`✨ AI generated & loaded sandboxed command: ${cleanName}`);

      res.json({
        success: true,
        message: result.message,
        code,
        loaded: result.loaded,
      });
    } catch (error: any) {
      addLog(`❌ AI Command Generation failed: ${error.message}`);
      res.status(500).json({ error: `AI generation failed: ${error.message}` });
    }
  });

  // ---------------------------------------------------------------------------
  // API: Download complete ready-to-run bot package as a ZIP!
  // ---------------------------------------------------------------------------
  const CONFIG_IMPORT_RE = /import\s+({[^}]+})\s+from\s+['"]\.\.\/config\.js['"];?/g;
  const CONFIG_SHIM = "const config = require('../config.json');\nconst getConfig = () => config;\nconst updateConfig = () => {};";

  function regexTranspile(source: string): string {
    let js = source;
    // Type-only imports (safe to drop)
    js = js.replace(/import\s+[^;]+?\s+from\s+['"]\.\.\/types\.js['"];?/g, "");
    // Project helper imports (resolved to root-level lib files in the zip)
    js = js.replace(/import\s+({[^}]+})\s+from\s+['"]\.\.\/geminiClient\.js['"];?/g, "const $1 = require('./geminiClient.js');");
    js = js.replace(/import\s+({[^}]+})\s+from\s+['"]\.\.\/database\.js['"];?/g, "const $1 = require('./database.js');");
    // Named imports from npm / other modules
    js = js.replace(/import\s+({[^}]+})\s+from\s+["']@google\/genai["'];?/g, "const $1 = require('@google/genai');");
    js = js.replace(/import\s+({[^}]+})\s+from\s+["']([^"']+)["'];?/g, "const $1 = require('$2');");
    js = js.replace(/import\s+([A-Za-z_$][\w$]*)\s+from\s+["']([^"']+)["'];?/g, "const $1 = require('$2');");
    // Exports and TS-only syntax
    js = js.replace(/export\s+default\s+(\w+);?/g, "module.exports = $1;");
    js = js.replace(/export\s+interface\s+\w+\s*\{[^}]*\}/g, "");
    js = js.replace(/export\s+const\s+(\w+)(:\s*[\w<>|'"]+)?\s*=/g, "const $1 =");
    js = js.replace(/export\s+async\s+function\s+(\w+)/g, "async function $1");
    js = js.replace(/export\s+function\s+(\w+)/g, "function $1");
    js = js.replace(/const\s+(\w+):\s*BotCommand\s*=/g, "const $1 =");
    js = js.replace(/:\s*BotCommand\b/g, "");
    js = js.replace(/:\s*BotCommandContext\b/g, "");
    return js;
  }

  /**
   * Converts a TypeScript source file to CommonJS for the exported package.
   * Prefers esbuild (handles all TS syntax correctly); falls back to a
   * conservative regex transpiler when esbuild is unavailable.
   */
  async function transpileTsToCjs(source: string): Promise<string> {
    // Rewrite config.ts imports to read the packaged config.json.
    const preprocessed = source.replace(CONFIG_IMPORT_RE, CONFIG_SHIM);
    try {
      const { transform } = await import("esbuild");
      const result = await transform(preprocessed, {
        loader: "ts",
        format: "cjs",
        platform: "node",
        target: "node18",
      });
      return result.code;
    } catch (e: any) {
      console.warn("[ZIP] esbuild transform unavailable; using regex transpiler:", e?.message || e);
      return regexTranspile(preprocessed);
    }
  }

  app.get("/api/bot/download-zip", async (req, res) => {
    addLog("📦 Packaging Nebula Bot for local download...");

    try {
      const zip = new AdmZip();

      // 1. Generate local start file: index.js
      const indexJs = `/**
 * Nebula Bot Local Startup File
 * Powered by @whiskeysockets/baileys
 */

const { default: makeWASocket, useMultiFileAuthState, DisconnectReason, fetchLatestBaileysVersion } = require("@whiskeysockets/baileys");
const pino = require("pino");
const { Boom } = require("@hapi/boom");
const dotenv = require("dotenv");
const path = require("path");
const fs = require("fs");

dotenv.config();

const config = require("./config.json");

// Command Registry
const commands = new Map();

function loadCommands() {
  const commandsDir = path.join(__dirname, "commands");
  if (!fs.existsSync(commandsDir)) return;
  
  const files = fs.readdirSync(commandsDir);
  for (const file of files) {
    if (!file.endsWith(".js")) continue;
    try {
      const cmdPath = path.join(commandsDir, file);
      delete require.cache[require.resolve(cmdPath)];
      const cmd = require(cmdPath);
      // Support both ES default and CJS exports
      const command = cmd.default || cmd;
      if (command && command.name) {
        commands.set(command.name.toLowerCase(), command);
        console.log(\`🔮 Loaded command: \${command.name}\`);
      }
    } catch (err) {
      console.error(\`❌ Failed to load command file \${file}:\`, err.message);
    }
  }
  // Expose registered commands list globally for menu
  global.botCommands = Array.from(commands.values());
}

async function startBot() {
  console.log("🌌 Starting Nebula Bot...");
  loadCommands();

  const { state, saveCreds } = await useMultiFileAuthState("auth_session");
  const { version } = await fetchLatestBaileysVersion();

  const sock = makeWASocket({
    version,
    auth: state,
    printQRInTerminal: true, // Output QR in terminal for easy local scanning
    logger: pino({ level: "info" }),
    browser: [config.browserPlatform || "Ubuntu", config.browserName || "Chrome", config.browserVersion || "22.04.4"],
  });

  sock.ev.on("connection.update", (update) => {
    const { connection, lastDisconnect, qr } = update;
    if (connection === "open") {
      console.log("✅ Nebula Bot connected successfully! Type .menu in chat to start.");
    }
    if (connection === "close") {
      const shouldReconnect = (lastDisconnect.error instanceof Boom) ? lastDisconnect.error.output.statusCode !== DisconnectReason.loggedOut : true;
      console.log(\`❌ Connection closed. Reconnecting: \${shouldReconnect}\`);
      if (shouldReconnect) {
        startBot();
      }
    }
  });

  sock.ev.on("creds.update", saveCreds);

  sock.ev.on("messages.upsert", async (m) => {
    if (m.type !== "notify") return;
    for (const msg of m.messages) {
      if (!msg.message || msg.key.fromMe) continue;

      const text = msg.message.conversation || 
                   msg.message.extendedTextMessage?.text || 
                   msg.message.imageMessage?.caption || 
                   msg.message.videoMessage?.caption || 
                   "";

      const prefix = config.prefix;
      if (!text.startsWith(prefix)) continue;

      const senderJid = msg.key.remoteJid;
      const senderNumber = senderJid.split("@")[0];
      const senderName = msg.pushName || "User";

      const body = text.slice(prefix.length).trim();
      const args = body.split(/\\s+/);
      const commandName = args.shift().toLowerCase();

      const command = commands.get(commandName);
      if (!command) continue;

      const isOwner = senderNumber === config.ownerNumber.replace(/[^0-9]/g, "");

      const context = {
        sender: senderJid,
        senderName,
        isOwner,
        isAdmin: isOwner, // local runner treats the owner as admin
        prefix,
        commandName,
        args,
        fullMessage: text,
        reply: async (textStr, mediaUrl) => {
          if (mediaUrl) {
            return await sock.sendMessage(senderJid, { image: { url: mediaUrl }, caption: textStr }, { quoted: msg });
          }
          return await sock.sendMessage(senderJid, { text: textStr }, { quoted: msg });
        },
        react: async (emoji) => {
          return await sock.sendMessage(senderJid, { react: { text: emoji, key: msg.key } });
        }
      };

      try {
        await command.execute(sock, msg, context);
      } catch (err) {
        console.error(\`Error in \${commandName}:\`, err);
        context.reply(\`❌ Error in \${commandName}: \` + err.message);
      }
    }
  });
}

startBot();
`;

      // 2. Generate package.json for local
      const packageJson = {
        name: "nebula-bot-local",
        version: "1.1.0",
        description: "Nebula Bot - Lightweight WhatsApp Multi-Device Bot",
        main: "index.js",
        scripts: {
          start: "node index.js",
        },
        dependencies: {
          "@whiskeysockets/baileys": "^7.0.0-rc14",
          "@hapi/boom": "^9.1.4",
          "pino": "^10.3.1",
          "dotenv": "^17.2.3",
          "@google/genai": "^2.4.0",
          "qrcode": "^1.5.4"
        }
      };

      // 3. Generate README.md
      const readmeMd = `# 🌌 Nebula Bot - WhatsApp Multi-Device

A highly lightweight and modular WhatsApp Multi-Device Bot.

## 🚀 Quick Local Installation

1. Make sure you have **Node.js 18 or newer** installed.
2. Extract the downloaded ZIP file into a clean folder.
3. Open your terminal in the extracted folder and run:
   \`\`\`bash
   npm install
   \`\`\`
4. Configure your environment variables in \`.env\`:
   \`\`\`env
   GEMINI_API_KEY="YOUR_API_KEY_HERE"
   \`\`\`
5. Start the bot:
   \`\`\`bash
   npm start
   \`\`\`
6. A WhatsApp QR Code will print in your terminal. Scan it using **Linked Devices** on your phone!

## 🔮 Customization & Commands

- **Config File:** Edit \`config.json\` to customize prefix, bot name, bot image, and channel details.
- **Add Features:** All commands are loaded dynamically from the \`commands/\` folder. To create a new command, just add a new \`.js\` file into the \`commands/\` folder exporting a command structure!
- **Admin commands** (\`antilink\`, \`antitag\`, \`hidetag\`) are available to the owner in this local runner.

## ⚠️ Security Note

The \`.env\` file contains a placeholder API key. Set your real \`GEMINI_API_KEY\` before using AI features. Never share your \`.env\` or \`auth_session/\` folder.
`;

      // Add files to Zip
      zip.addFile("index.js", Buffer.from(indexJs), "Main local runner");
      zip.addFile("package.json", Buffer.from(JSON.stringify(packageJson, null, 2)), "Dependencies list");
      const exportedConfig: any = { ...getConfig() };
      delete exportedConfig.sessionString; // M2: never export session material
      zip.addFile("config.json", Buffer.from(JSON.stringify(exportedConfig, null, 2)), "Custom configuration settings");
      zip.addFile("README.md", Buffer.from(readmeMd), "Documentation");

      // Environment template — NEVER embeds the live API key.
      const localEnv = `GEMINI_API_KEY="MY_GEMINI_API_KEY"\n# Set your real Gemini API key here to enable AI features.\n`;
      zip.addFile(".env", Buffer.from(localEnv), "Environment configuration");

      // Shared runtime modules used by the commands (transpiled to CJS).
      for (const libFile of ["geminiClient.ts", "database.ts"]) {
        const libPath = path.join(process.cwd(), "src", "bot", libFile);
        if (fs.existsSync(libPath)) {
          const jsContent = await transpileTsToCjs(fs.readFileSync(libPath, "utf-8"));
          zip.addFile(libFile.replace(".ts", ".js"), Buffer.from(jsContent), "Shared runtime module");
        }
      }

      // Copy command files into ZIP (TypeScript -> CommonJS)
      const commandsDir = getCommandsDir();
      if (fs.existsSync(commandsDir)) {
        const files = fs.readdirSync(commandsDir);
        for (const file of files) {
          if (!file.endsWith(".ts")) continue;
          const filePath = path.join(commandsDir, file);
          const jsContent = await transpileTsToCjs(fs.readFileSync(filePath, "utf-8"));
          zip.addFile(`commands/${file.replace(".ts", ".js")}`, Buffer.from(jsContent), "Command logic file");
        }
      }

      const zipBuffer = zip.toBuffer();

      res.set({
        "Content-Type": "application/zip",
        "Content-Disposition": "attachment; filename=nebula-bot-local.zip",
        "Content-Length": zipBuffer.length
      });

      res.send(zipBuffer);
      addLog("✅ Nebula Bot ZIP compiled and sent to user successfully!");
    } catch (error: any) {
      addLog(`❌ Failed to compile ZIP download: ${error.message}`);
      res.status(500).json({ error: `ZIP packing failed: ${error.message}` });
    }
  });

  // ---------------------------------------------------------------------------
  // API: Audio Transcription using Gemini with fallback models
  // ---------------------------------------------------------------------------
  const ALLOWED_AUDIO_MIMES = [
    "audio/webm", "audio/mp4", "audio/mpeg", "audio/mp3",
    "audio/ogg", "audio/wav", "audio/x-wav", "audio/aac", "audio/x-m4a",
  ];
  const MAX_AUDIO_BASE64 = 30_000_000; // ~22 MB of binary audio

  app.post("/api/gemini/transcribe", async (req, res) => {
    const { audioBase64, mimeType } = req.body;
    if (typeof audioBase64 !== "string" || !audioBase64) {
      return res.status(400).json({ error: "Missing audioBase64 payload" });
    }
    if (audioBase64.length > MAX_AUDIO_BASE64) {
      return res.status(413).json({ error: "Audio payload too large (max ~22MB of audio)." });
    }
    const mime = (typeof mimeType === "string" ? mimeType : "audio/webm").toLowerCase();
    if (!ALLOWED_AUDIO_MIMES.includes(mime)) {
      return res.status(400).json({ error: `Unsupported audio mime type "${mime}".` });
    }

    const ai = getAIClient();
    if (!ai) {
      return res.status(400).json({ error: "Gemini API key is not configured. Please add it to Settings > Secrets." });
    }

    const transcriptionModels = ["gemini-3.5-flash", "gemini-2.5-flash", "gemini-1.5-flash"];
    let lastError: any = null;

    for (const model of transcriptionModels) {
      try {
        const response = await ai.models.generateContent({
          model,
          contents: [
            {
              inlineData: {
                data: audioBase64,
                mimeType: mime,
              },
            },
            { text: "Accurately transcribe this audio message. Output only the plain transcription, no extra commentary, preambles, or punctuation headers." },
          ],
        });

        if (response && response.text) {
          return res.json({ transcript: response.text.trim() });
        }
      } catch (err: any) {
        console.warn(`⚠️ Transcription failed on model [${model}]:`, err?.message || err);
        lastError = err;
      }
    }

    res.status(500).json({ error: `Transcription failed across all fallback models: ${lastError?.message || lastError}` });
  });

  // ---------------------------------------------------------------------------
  // API: Real-time Voice Conversation using Gemini with fallbacks and TTS
  // ---------------------------------------------------------------------------
  app.post("/api/gemini/voice-conversation", async (req, res) => {
    const { prompt } = req.body;
    if (typeof prompt !== "string" || !prompt.trim()) {
      return res.status(400).json({ error: "Missing prompt query" });
    }
    if (prompt.length > 5000) {
      return res.status(400).json({ error: "Prompt is too long (max 5000 characters)." });
    }

    const ai = getAIClient();
    if (!ai) {
      return res.status(400).json({ error: "Gemini API key is not configured. Please add it to Settings > Secrets." });
    }

    try {
      // 1. Generate textual spoken reply using robust text fallback generator helper
      const replyText = await generateTextWithFallback(
        prompt,
        "You are a friendly, helpful, highly conversational AI voice assistant. Keep your responses super short (1-2 sentences), sweet, warm, and direct. Avoid asterisks, bullets, lists, markdown formatting, or emojis since your response will be read aloud.",
        "gemini-3.5-flash"
      );

      // 2. Synthesize spoken reply to audio using TTS preview model
      let audioBase64: string | null = null;
      try {
        const speechResponse = await ai.models.generateContent({
          model: "gemini-3.1-flash-tts-preview",
          contents: [{ parts: [{ text: replyText }] }],
          config: {
            responseModalities: ["AUDIO"],
            speechConfig: {
              voiceConfig: {
                prebuiltVoiceConfig: { voiceName: "Zephyr" },
              },
            },
          },
        });
        audioBase64 = speechResponse.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data || null;
      } catch (ttsErr: any) {
        console.warn("⚠️ TTS audio synthesis rate-limited or busy. Falling back to text-only spoken reply.", ttsErr?.message || ttsErr);
      }

      res.json({
        text: replyText,
        audioBase64
      });
    } catch (error: any) {
      console.error("Voice conversation error:", error);
      res.status(500).json({ error: error.message || error });
    }
  });

  // ---------------------------------------------------------------------------
  // API: Batch Download Management, Real-time Status & Storage Optimization
  // ---------------------------------------------------------------------------
  app.get("/api/batch-downloads", (req, res) => {
    res.json({
      jobs: getAllBatchJobs(),
      storage: getTempStorageStats()
    });
  });

  app.get("/api/batch-downloads/:id", (req, res) => {
    const job = getBatchJob(req.params.id);
    if (!job) {
      return res.status(404).json({ error: "Batch download job not found." });
    }
    res.json(job);
  });

  app.post("/api/batch-downloads/simulate", (req, res) => {
    const { animeTitle, season, totalEpisodes, resolution, language } = req.body || {};
    const job = simulateBatchDownload({
      animeTitle: typeof animeTitle === "string" ? animeTitle.slice(0, 80) : undefined,
      season: typeof season === "string" ? season.slice(0, 30) : undefined,
      totalEpisodes: typeof totalEpisodes === "number" ? Math.min(12, Math.max(1, totalEpisodes)) : 5,
      resolution: typeof resolution === "string" ? resolution : undefined,
      language: typeof language === "string" ? language : undefined,
    });
    addLog(`🚀 [Batch Download] Started concurrent batch job for "${job.animeTitle} - ${job.season}" (${job.totalEpisodes} episodes)`);
    res.json({ success: true, job });
  });

  app.post("/api/batch-downloads/cancel/:id", (req, res) => {
    const success = cancelBatchJob(req.params.id);
    if (!success) {
      return res.status(404).json({ error: "Batch job not found or already ended." });
    }
    res.json({ success: true, message: "Batch download cancelled." });
  });

  app.post("/api/batch-downloads/retry/:id", (req, res) => {
    const result = retryBatchJob(req.params.id);
    if (!result.success) {
      return res.status(404).json({ error: result.error || "Batch job not found." });
    }
    addLog(`🔄 [Batch Download] Initiated retry for batch job ${req.params.id} ("${result.job?.animeTitle}")`);
    res.json({ success: true, job: result.job });
  });

  app.post("/api/batch-downloads/retry-episode/:id/:epNum", (req, res) => {
    const epNum = parseInt(req.params.epNum, 10);
    const result = retryEpisode(req.params.id, epNum);
    if (!result.success) {
      return res.status(404).json({ error: result.error || "Failed to retry episode." });
    }
    addLog(`🔄 [Batch Download] Retrying episode ${epNum} for batch job ${req.params.id}`);
    res.json({ success: true, job: result.job });
  });

  app.post("/api/batch-downloads/simulate-error/:id", (req, res) => {
    const { errorType, epNum } = req.body || {};
    const result = injectSimulatedError(req.params.id, errorType === "episode" ? "episode" : "network", epNum);
    if (!result.success) {
      return res.status(404).json({ error: result.error || "Batch job not found." });
    }
    addLog(`⚠️ [Batch Download] Injected simulated ${errorType || "network"} error into batch job ${req.params.id}`);
    res.json({ success: true, job: result.job });
  });

  app.post("/api/batch-downloads/cleanup", (req, res) => {
    const result = cleanupExpiredZipFiles();
    addLog(`🧹 [Storage Cleanup] Manual purge executed: ${result.cleanedFiles} files cleaned up, ${result.freedMB} MB freed.`);
    res.json({
      success: true,
      result,
      storage: getTempStorageStats()
    });
  });

  app.get("/api/batch-downloads-stats", (req, res) => {
    res.json(getTempStorageStats());
  });

  // ---------------------------------------------------------------------------
  // Public Temporary Media Download Route (Time-limited, secure tokens, Range support)
  // ---------------------------------------------------------------------------
  const handleTempDownload = (req: Request, res: Response) => {
    // Set permissive CORS headers for seamless direct browser downloads
    res.setHeader("Access-Control-Allow-Origin", "*");
    res.setHeader("Access-Control-Allow-Methods", "GET, HEAD, OPTIONS");
    res.setHeader("Access-Control-Allow-Headers", "Range, Content-Type, Accept");
    res.setHeader("Access-Control-Expose-Headers", "Content-Length, Content-Range, Content-Disposition, Accept-Ranges");

    if (req.method === "OPTIONS") {
      return res.status(204).end();
    }

    const token = req.params.token;
    if (!token || typeof token !== "string") {
      return res.status(400).json({ error: "Invalid or missing download token." });
    }

    const record = getTempDownload(token);
    if (!record || !fs.existsSync(record.filePath)) {
      if (req.accepts("html")) {
        return res.status(410).send(`
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Download Expired - Nebula Bot</title>
            <style>
              body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: #0f172a; color: #f8fafc; display: flex; align-items: center; justify-content: center; min-height: 100vh; margin: 0; padding: 20px; }
              .card { background: #1e293b; border: 1px solid #334155; border-radius: 12px; padding: 32px; max-width: 480px; text-align: center; box-shadow: 0 20px 25px -5px rgba(0,0,0,0.5); }
              h1 { color: #f43f5e; font-size: 24px; margin-bottom: 12px; }
              p { color: #94a3b8; line-height: 1.6; margin-bottom: 24px; }
              .badge { display: inline-block; background: #334155; color: #cbd5e1; padding: 6px 14px; border-radius: 9999px; font-size: 13px; font-family: monospace; }
            </style>
          </head>
          <body>
            <div class="card">
              <h1>⏳ Download Link Expired</h1>
              <p>This temporary download link has expired or the file has been purged for storage security. Please request a fresh download via the WhatsApp bot.</p>
              <div class="badge">Nebula Secure Media Engine</div>
            </div>
          </body>
          </html>
        `);
      }
      return res.status(410).json({ error: "This temporary download link has expired or is invalid." });
    }

    // Increment download counter
    record.downloadCount = (record.downloadCount || 0) + 1;

    const filePath = record.filePath;
    let fileSize = record.sizeBytes;
    try {
      const stat = fs.statSync(filePath);
      fileSize = stat.size;
    } catch {
      // Fallback to record.sizeBytes if already known
    }

    const range = req.headers.range;

    res.setHeader("Accept-Ranges", "bytes");
    res.setHeader("Content-Type", record.mimeType || "application/octet-stream");
    res.setHeader("Cache-Control", "private, no-cache, no-store, must-revalidate");

    const encodedFilename = encodeURIComponent(record.filename).replace(/['()]/g, escape);
    const dispositionType = req.query.inline === "true" ? "inline" : "attachment";
    res.setHeader(
      "Content-Disposition",
      `${dispositionType}; filename="${record.filename}"; filename*=UTF-8''${encodedFilename}`
    );

    if (req.method === "HEAD") {
      res.setHeader("Content-Length", fileSize);
      return res.status(200).end();
    }

    if (range) {
      const parts = range.replace(/bytes=/, "").split("-");
      const start = parseInt(parts[0], 10);
      const end = parts[1] ? parseInt(parts[1], 10) : fileSize - 1;

      if (isNaN(start) || start >= fileSize || end >= fileSize || start > end) {
        res.setHeader("Content-Range", `bytes */${fileSize}`);
        return res.status(416).end();
      }

      const chunksize = end - start + 1;
      const fileStream = fs.createReadStream(filePath, { start, end });

      res.writeHead(206, {
        "Content-Range": `bytes ${start}-${end}/${fileSize}`,
        "Content-Length": chunksize,
      });

      fileStream.pipe(res);
    } else {
      res.setHeader("Content-Length", fileSize);
      const fileStream = fs.createReadStream(filePath);
      fileStream.pipe(res);
    }
  };

  app.get("/api/media/download/:token", handleTempDownload);
  app.head("/api/media/download/:token", handleTempDownload);
  app.options("/api/media/download/:token", handleTempDownload);
  app.get("/d/:token", handleTempDownload);
  app.head("/d/:token", handleTempDownload);
  app.options("/d/:token", handleTempDownload);

  // JSON body / payload error handling as clean JSON instead of HTML
  app.use((err: any, req: Request, res: Response, next: NextFunction) => {
    if (err?.type === "entity.too.large") {
      return res.status(413).json({ error: "Request body too large." });
    }
    if (err?.type === "entity.parse.failed") {
      return res.status(400).json({ error: "Invalid JSON body." });
    }
    next(err);
  });

  return app;
}
