import { describe, expect, it } from "vitest";
import fs from "fs";
import base64Command from "../src/bot/commands/base64.js";

/**
 * 8.84 — correctifs de l'audit ultra-complet des commandes
 * (AUDIT_COMMANDS_2026-09-26.md, C2-C8).
 *
 * C2 : song télécharge côté serveur une URL renvoyée par un tiers → garde
 *      SSRF (urlSafety.isSafeDownloadUrl) obligatoire avant le fetch.
 * C3 : la vue « code » du panneau doit être honnête (alias → vraie commande,
 *      anime → novabox.ts, plus de faux code autogénéré).
 * C4 : define a un timeout (fetch nu avant).
 * C5 : instagram borne son scraper (aucun timeout intégré avant).
 * C6 : whois fonctionne en chat privé (avant : « pas dans le groupe »).
 * C7 : badge owner par comparaison EXACTE (avant : sous-chaîne).
 * C8 : base64 frombinary refuse une entrée non binaire (avant : caractères
 *      NUL silencieux) — testé en COMPORTEMENT ci-dessous.
 */

function read(file: string): string {
  return fs.readFileSync(file, "utf-8");
}

describe("C2 — song : garde SSRF sur l'URL de téléchargement", () => {
  it("valide l'URL via isSafeDownloadUrl AVANT le axios.get serveur", () => {
    const src = read("src/bot/commands/song.ts");
    expect(src).toContain('from "../urlSafety.js"');
    const guardPos = src.indexOf("await isSafeDownloadUrl(url)");
    const fetchPos = src.indexOf("await axios.get(url,");
    expect(guardPos).toBeGreaterThan(-1);
    expect(fetchPos).toBeGreaterThan(guardPos);
  });
});

describe("C3 — vue code du panneau honnête", () => {
  it("résout l'alias vers la vraie commande + mapping anime → novabox.ts", () => {
    const src = read("app.ts");
    expect(src).toContain("const realName = cmd.name.toLowerCase();");
    expect(src).toContain('anime: "novabox.ts"');
    expect(src).toContain("getPanelCommandSource(realName)");
  });

  it("plus de FAUX code autogénéré — note honnête à la place", () => {
    const src = read("app.ts");
    expect(src).not.toContain("Autogenerated dynamic code fallback");
    expect(src).toContain("Source non disponible pour cette commande intégrée.");
  });
});

describe("C4/C5 — timeouts des commandes réseau", () => {
  it("define : fetch avec AbortSignal.timeout", () => {
    expect(read("src/bot/commands/define.ts")).toContain("AbortSignal.timeout(20000)");
  });

  it("instagram : scraper borné par Promise.race", () => {
    const src = read("src/bot/commands/instagram.ts");
    expect(src).toContain("Promise.race");
    expect(src).toContain("igdl timeout");
  });
});

describe("C6/C7 — whois en privé + badge owner exact", () => {
  it("chat privé : plus d'exigence d'appartenance au groupe", () => {
    const src = read("src/bot/commands/whois.ts");
    expect(src).toContain('from.endsWith("@g.us")');
    expect(src).toContain("Contact (chat privé)");
    expect(src).toContain("isGroup && !participant");
  });

  it("badge owner : comparaison exacte, plus de sous-chaîne", () => {
    const src = read("src/bot/commands/whois.ts");
    expect(src).toContain("ownerNumbers.includes(number)");
    expect(src).not.toContain("ownerCfg.includes(number)");
  });
});

describe("C8 — base64 frombinary strict (comportement)", () => {
  async function run(args: string[]): Promise<string> {
    const replies: string[] = [];
    const context: any = {
      args,
      reply: async (t: string) => {
        replies.push(t);
      },
      react: async () => {},
    };
    await base64Command.execute(undefined as any, {} as any, context);
    return replies[0] || "";
  }

  it("refuse une entrée non binaire avec un message clair", async () => {
    const out = await run(["frombinary", "abc", "def"]);
    expect(out).toContain("binaire invalide");
  });

  it("accepte et décode une entrée binaire valide", async () => {
    const out = await run(["frombinary", "01001000", "01101001"]);
    expect(out).toContain("Hi");
  });

  it("les autres actions restent intactes (rot13, encode)", async () => {
    expect(await run(["rot13", "Uryyb"])).toContain("Hello");
    expect(await run(["encode", "Hi"])).toContain("SGk=");
  });
});
