import crypto from "crypto";
import { recordAudit } from "./auditTrail.js";
import type { NextFunction, Request, Response } from "express";

/**
 * Panel authentication.
 *
 * Threat model fixed by this module (was: public /auth/token + cosmetic
 * cookie hand-out):
 *  - The panel access key (PANEL_TOKEN) is NEVER exposed via an endpoint.
 *    The operator enters it once in the UI; the server issues a random,
 *    HttpOnly session cookie that carries no secret.
 *  - API tooling keeps using `Authorization: Bearer <PANEL_TOKEN>`.
 *  - CSRF: cookie-authenticated state-changing requests must carry an
 *    Origin/Referer matching the app's own host (or APP_URL). Bearer
 *    requests are exempt (an attacker cannot read the bearer token).
 */

const SESSION_TTL_MS = 12 * 60 * 60 * 1000; // 12 hours, sliding
const MAX_SESSIONS = 100;
const SESSION_COOKIE = "panel_session";

export interface PanelAuth {
  /** Express middleware guarding /api/* endpoints. */
  requireApiAuth(req: Request, res: Response, next: NextFunction): void;
  /** Middleware that records the detected host; placed before everything else. */
  hostProbe(req: Request, res: Response, next: NextFunction): void;
  login(token: string): { success: boolean; sessionId?: string; error?: string };
  logout(req: Request, res: Response): void;
  isAuthenticated(req: Request): boolean;
  sweep(): void;
  sessionCookieName: string;
  getSessionCount(): number;
  setCookie(res: Response, sessionId: string): void;
  clearCookie(res: Response): void;
}

interface SessionRecord {
  id: string;
  createdAt: number;
  expiresAt: number;
}

export function createPanelAuth(opts: {
  configuredToken: string;
  autoGenerated: boolean;
  appUrl?: string;
}): PanelAuth {
  const sessions = new Map<string, SessionRecord>();

  function readCookie(req: Request, name: string): string | null {
    const raw = req.headers.cookie || "";
    for (const part of raw.split(";")) {
      const eq = part.indexOf("=");
      if (eq === -1) continue;
      const key = part.slice(0, eq).trim();
      if (key === name) {
        try {
          return decodeURIComponent(part.slice(eq + 1).trim());
        } catch {
          return null;
        }
      }
    }
    return null;
  }

  function timingSafeEqual(a: string, b: string): boolean {
    const ba = Buffer.from(a, "utf-8");
    const bb = Buffer.from(b, "utf-8");
    if (ba.length !== bb.length) return false;
    return crypto.timingSafeEqual(ba, bb);
  }

  function validBearer(req: Request): boolean {
    const bearer = (req.headers.authorization || "").replace(/^Bearer\s+/i, "");
    return !!bearer && timingSafeEqual(bearer, opts.configuredToken);
  }

  function validSession(req: Request): SessionRecord | null {
    const id = readCookie(req, SESSION_COOKIE);
    if (!id) return null;
    const record = sessions.get(id);
    if (!record) return null;
    const now = Date.now();
    if (record.expiresAt < now) {
      sessions.delete(id);
      return null;
    }
    // Sliding expiration.
    record.expiresAt = now + SESSION_TTL_MS;
    return record;
  }

  /**
   * CSRF protection for cookie-authenticated writes: the request must come
   * from the panel's own origin (same host, or the configured APP_URL).
   * Requests without a session cookie (bearer auth) are exempt.
   */
  function splitHostPort(host: string, protocol: string): { hostname: string; port: string } {
    const lower = host.toLowerCase();
    const defaultPort = protocol === "https:" ? "443" : "80";
    // IPv6 literal: [::1] or [::1]:8080
    const v6 = lower.match(/^\[([^\]]+)\](?::(\d+))?$/);
    if (v6) return { hostname: v6[1], port: v6[2] || defaultPort };
    const lastColon = lower.lastIndexOf(":");
    if (lastColon !== -1 && lower.indexOf(":") === lastColon) {
      return { hostname: lower.slice(0, lastColon), port: lower.slice(lastColon + 1) || defaultPort };
    }
    return { hostname: lower, port: defaultPort };
  }

  function originAllowed(req: Request): boolean {
    const origin = req.headers.origin;
    const referer = req.headers.referer;
    const source = origin || referer;
    if (!source) {
      // Non-browser clients (curl, supertest) without a session cookie never
      // get here; a browser always sends Origin on cross-origin writes and
      // Referer on same-origin navigations. Fail closed for cookies.
      return false;
    }
    if (source === "null") return false;

    let sourceUrl: URL;
    try {
      sourceUrl = new URL(source);
    } catch {
      return false;
    }

    const requestProtocol = req.protocol === "https" ? "https:" : "http:";
    const candidates: Array<{ hostname: string; port: string }> = [];
    const requestHost = req.get("host");
    if (requestHost) candidates.push(splitHostPort(requestHost, requestProtocol));
    if (opts.appUrl) {
      try {
        const app = new URL(opts.appUrl);
        candidates.push(splitHostPort(app.host, app.protocol));
      } catch {
        // Ignore malformed APP_URL; request host still applies.
      }
    }

    const sourceSpecifiesPort = sourceUrl.port !== "";
    const sourceParts = splitHostPort(sourceUrl.host, sourceUrl.protocol);
    return candidates.some(
      (c) =>
        c.hostname === sourceParts.hostname &&
        (sourceSpecifiesPort ? c.port === sourceParts.port : true)
    );
  }

  const auth: PanelAuth = {
    sessionCookieName: SESSION_COOKIE,
    hostProbe(req, _res, next) {
      // Record host for generating valid absolute temporary download URLs.
      if (req.headers.host) {
        // Updated by app.ts via updateServerBaseUrl (kept there to avoid a
        // dependency cycle with tempDownloadManager).
        next();
        return;
      }
      next();
    },

    requireApiAuth(req, res, next) {
      const viaCookie = validSession(req) !== null;
      const viaBearer = validBearer(req);

      if (viaBearer) return next();

      if (viaCookie) {
        // Writes via cookie need a same-origin check.
        const isSafeMethod = req.method === "GET" || req.method === "HEAD" || req.method === "OPTIONS";
        if (!isSafeMethod && !originAllowed(req)) {
          return res.status(403).json({
            error: "Forbidden: cross-site request rejected (origin check failed).",
          });
        }
        return next();
      }

      return res.status(401).json({
        error: "Unauthorized: a valid panel session or PANEL_TOKEN is required to access the bot API.",
      });
    },

    login(token) {
      if (typeof token !== "string" || !token) {
        return { success: false, error: "Access key is required." };
      }
      if (!timingSafeEqual(token, opts.configuredToken)) {
        recordAudit("panel", "auth.login_failed", "panel", "Invalid access key attempt");
        return { success: false, error: "Invalid access key." };
      }
      // Evict old sessions when at capacity.
      if (sessions.size >= MAX_SESSIONS) {
        const oldest = [...sessions.values()].sort((a, b) => a.createdAt - b.createdAt)[0];
        if (oldest) sessions.delete(oldest.id);
      }
      const id = crypto.randomBytes(32).toString("hex");
      const now = Date.now();
      sessions.set(id, { id, createdAt: now, expiresAt: now + SESSION_TTL_MS });
      recordAudit("panel", "auth.login", "panel", `Session ${id.slice(0, 8)}… issued`);
      return { success: true, sessionId: id };
    },

    logout(req, res) {
      const id = readCookie(req, SESSION_COOKIE);
      if (id) {
        sessions.delete(id);
        recordAudit("panel", "auth.logout", "panel", `Session ${id.slice(0, 8)}… ended`);
      }
      auth.clearCookie(res);
    },

    isAuthenticated(req) {
      return validSession(req) !== null || validBearer(req);
    },

    sweep() {
      const now = Date.now();
      for (const [id, record] of sessions) {
        if (record.expiresAt < now) sessions.delete(id);
      }
    },

    getSessionCount() {
      return sessions.size;
    },

    setCookie(res, sessionId) {
      res.cookie(SESSION_COOKIE, sessionId, {
        httpOnly: true,
        sameSite: "none",
        secure: true,
        path: "/",
        maxAge: SESSION_TTL_MS,
      });
    },

    clearCookie(res) {
      res.clearCookie(SESSION_COOKIE, {
        httpOnly: true,
        sameSite: "none",
        secure: true,
        path: "/",
      });
    },
  };

  return auth;
}
