import express, { NextFunction, Request, Response } from "express";
import path from "path";
import fs from "fs";
import crypto from "crypto";
import { createPanelAuth } from "../bot/panelAuth.js";
import type { BotOverview } from "../bot/botSupervisor.js";

/**
 * Multi-bots (8.75) — application panneau du process SUPERVISEUR.
 *
 * En production (server.ts), ce panneau remplace l'app mono-bot : il ne
 * contient PLUS de moteur en interne. Il garde les surfaces globales (login,
 * santé, archive projet, liste des bots) et proxifie toutes les routes par-bot
 * (état WhatsApp, pairing, commandes, batchs…) vers le moteur enfant ciblé
 * via le superviseur.
 *
 * Le frontend existant continue de fonctionner sans modification : sans
 * sélecteur `?bot=`, les requêtes partent vers le bot par défaut (le premier
 * activé de bots.json — « nebula » avec les chemins historiques).
 */

/** Surface du superviseur utilisée par le panneau (stubable en tests). */
export interface PanelSupervisor {
  getOverview(): BotOverview[];
  getDefaultBotId(): string | null;
  hasBot(id: string): boolean;
  startBot(id: string): Promise<{ ok: boolean; error?: string }>;
  stopBot(id: string): Promise<{ ok: boolean; error?: string }>;
  restartBot(id: string): Promise<{ ok: boolean; error?: string }>;
  proxyRequest(botId: string, req: Request, res: Response): Promise<void>;
  proxyMediaProbe(req: Request, res: Response): Promise<void>;
  fetchWhatsAppStatuses(): Promise<Record<string, Record<string, unknown> | null>>;
  describeConfig(): { source: "default" | "file"; file?: string; error?: string; total: number; enabled: number };
}

export function createPanelApp(supervisor: PanelSupervisor): express.Express {
  const app = express();
  app.set("trust proxy", true);
  app.use(express.json({ limit: "32mb" }));

  const configuredToken = process.env.PANEL_TOKEN?.trim() || "";
  const panelToken = configuredToken || crypto.randomBytes(24).toString("hex");
  const tokenIsAutoGenerated = !configuredToken;

  // Security headers — identiques à app.ts (le panneau reste embarquable en
  // iframe ; la CSP scelle les origines script/style/connect).
  app.use((_req: Request, res: Response, next: NextFunction) => {
    const isProd = process.env.NODE_ENV === "production";
    res.setHeader("X-Content-Type-Options", "nosniff");
    res.setHeader("Referrer-Policy", "strict-origin-when-cross-origin");
    res.setHeader("Permissions-Policy", "camera=(), microphone=(), geolocation=(), payment=()");
    res.setHeader(
      "Content-Security-Policy",
      [
        "default-src 'self'",
        isProd ? "script-src 'self'" : "script-src 'self' 'unsafe-inline'",
        "style-src 'self' 'unsafe-inline'",
        "img-src 'self' data: blob: https:",
        "media-src 'self' blob: https:",
        "font-src 'self' data:",
        "connect-src 'self' ws: wss:",
        "object-src 'none'",
        "base-uri 'self'",
        "form-action 'self'",
      ].join("; "),
    );
    if (_req.secure || String(_req.headers["x-forwarded-proto"] || "") === "https") {
      res.setHeader("Strict-Transport-Security", "max-age=31536000; includeSubDomains");
    }
    next();
  });

  const panelAuth = createPanelAuth({
    configuredToken: panelToken,
    autoGenerated: tokenIsAutoGenerated,
    appUrl: process.env.APP_URL,
  });

  // M3 : validation du header Host quand APP_URL est configurée (anti
  // host-header poisoning) — copie conforme de app.ts.
  const allowedHostname = (() => {
    try {
      const u = new URL(process.env.APP_URL || "");
      return u.hostname.toLowerCase();
    } catch {
      return "";
    }
  })();
  app.use((req: Request, res: Response, next: NextFunction) => {
    if (allowedHostname) {
      const hostHeader = req.get("host") || "";
      const hostName = hostHeader.split(":")[0].replace(/^\[|\]$/g, "").toLowerCase();
      const trusted =
        hostName === allowedHostname || hostName === "localhost" || hostName === "127.0.0.1" || hostName === "::1";
      if (!trusted) {
        console.warn(`[Panel] Rejected request with foreign Host header: "${hostHeader}" (allowed: ${allowedHostname})`);
        return res.status(400).json({ error: "Invalid Host header." });
      }
    }
    next();
  });

  if (tokenIsAutoGenerated) {
    console.log(`🔑 Panel access key (auto-generated): ${panelToken}`);
    console.log("   Use it in the panel login screen, or set PANEL_TOKEN to choose your own.");
  }

  const sessionSweepTimer = setInterval(() => panelAuth.sweep(), 10 * 60 * 1000);
  sessionSweepTimer.unref();

  // ---------------------------------------------------------------------------
  // Rate limiting (même clément que app.ts : peer socket, plafond mémoire)
  // ---------------------------------------------------------------------------
  const MAX_RATE_LIMIT_KEYS = 5000;
  const buckets = new Map<string, { count: number; resetAt: number }>();

  function rateLimit(max: number, windowMs: number, keyPrefix?: string) {
    return (req: Request, res: Response, next: NextFunction) => {
      const peer = req.socket.remoteAddress || "unknown";
      // keyPrefix : bucket partagé entre plusieurs chemins (ex. tous les
      // liens médias) au lieu d'un bucket par chemin — sinon un scan de
      // jetons aléatoires obtenait un bucket neuf à chaque essai
      // (audit 8.76 / SEC-03).
      const key = `${keyPrefix ?? req.path}|${peer}`;
      const now = Date.now();
      const bucket = buckets.get(key);
      if (!bucket || bucket.resetAt < now) {
        if (buckets.size >= MAX_RATE_LIMIT_KEYS) {
          for (const [k, b] of buckets) {
            if (b.resetAt < now) buckets.delete(k);
          }
          if (buckets.size >= MAX_RATE_LIMIT_KEYS) {
            let pruned = 0;
            for (const k of buckets.keys()) {
              buckets.delete(k);
              if (++pruned > 200) break;
            }
          }
        }
        buckets.set(key, { count: 1, resetAt: now + windowMs });
        return next();
      }
      bucket.count++;
      if (bucket.count > max) {
        return res.status(429).json({ error: "Too many requests. Please slow down and try again shortly." });
      }
      next();
    };
  }

  app.use("/api", rateLimit(300, 60_000));
  app.post("/api/auth/login", rateLimit(8, 60_000));

  const sweepTimer = setInterval(() => {
    const now = Date.now();
    for (const [key, bucket] of buckets) {
      if (bucket.resetAt < now) buckets.delete(key);
    }
  }, 10 * 60 * 1000);
  sweepTimer.unref();

  // ---------------------------------------------------------------------------
  // Session panneau (login / logout / statut)
  // ---------------------------------------------------------------------------
  app.get("/auth/token", (_req, res) => {
    res.status(404).json({ error: "Not found." });
  });

  app.post("/api/auth/login", (req, res) => {
    const { token } = req.body ?? {};
    const result = panelAuth.login(token);
    if (!result.success || !result.sessionId) {
      return res.status(401).json({ error: result.error || "Login failed." });
    }
    panelAuth.setCookie(res, result.sessionId);
    res.json({ success: true });
  });

  app.post("/api/auth/logout", (req, res) => {
    panelAuth.logout(req, res);
    res.json({ success: true });
  });

  app.get("/api/auth/me", (req, res) => {
    res.json({ authenticated: panelAuth.isAuthenticated(req) });
  });

  // ---------------------------------------------------------------------------
  // Santé du panneau (sonde publique — aucune information sensible).
  // Le DÉTAIL de l'erreur bots.json n'est renvoyé qu'aux requêtes
  // authentifiées (audit 8.76 / SEC-02) : la sonde publique n'expose qu'un
  // booléen de validité.
  // ---------------------------------------------------------------------------
  app.get("/api/health", (req, res) => {
    const cfg = supervisor.describeConfig();
    const payload: Record<string, unknown> = {
      status: "ok",
      mode: "panel",
      uptimeSeconds: Math.floor(process.uptime()),
      pid: process.pid,
      nodeVersion: process.version,
      botsConfigured: cfg.total,
      botsEnabled: cfg.enabled,
      botsConfigValid: !cfg.error,
    };
    if (panelAuth.isAuthenticated(req)) {
      payload.botsConfigError = cfg.error || null;
      payload.botsConfigSource = cfg.source;
    }
    res.json(payload);
  });

  // ---------------------------------------------------------------------------
  // Authentification : tout /api est protégé SAUF les liens médias publics
  // (sondés à travers les moteurs sans cookie de session) et /api/auth/.
  // ---------------------------------------------------------------------------
  app.use((req: Request, res: Response, next: NextFunction) => {
    const isApi = req.path.startsWith("/api/");
    const isArchive = req.path === "/nebula-bot-latest.zip";
    if (!isApi && !isArchive) {
      return next();
    }
    if (req.path.startsWith("/api/media/download/") || req.path.startsWith("/d/")) {
      return next();
    }
    if (req.path.startsWith("/api/auth/")) {
      return next();
    }
    panelAuth.requireApiAuth(req, res, next);
  });

  // ---------------------------------------------------------------------------
  // API: vue multi-bots (liste + état process + état WhatsApp fusionné)
  // ---------------------------------------------------------------------------
  app.get("/api/bots", async (_req, res) => {
    const overview = supervisor.getOverview();
    const statuses = await supervisor.fetchWhatsAppStatuses();
    res.json({
      bots: overview.map((bot) => ({
        ...bot,
        whatsapp: statuses[bot.id] || null,
        isDefault: bot.id === supervisor.getDefaultBotId(),
      })),
      config: supervisor.describeConfig(),
    });
  });

  app.post("/api/bots/:id/start", async (req, res) => {
    const result = await supervisor.startBot(req.params.id);
    if (!result.ok) return res.status(400).json(result);
    res.json({ success: true, message: `Bot « ${req.params.id} » lancé.` });
  });

  app.post("/api/bots/:id/stop", async (req, res) => {
    const result = await supervisor.stopBot(req.params.id);
    if (!result.ok) return res.status(400).json(result);
    res.json({ success: true, message: `Bot « ${req.params.id} » arrêté.` });
  });

  app.post("/api/bots/:id/restart", async (req, res) => {
    const result = await supervisor.restartBot(req.params.id);
    if (!result.ok) return res.status(400).json(result);
    res.json({ success: true, message: `Bot « ${req.params.id} » redémarré.` });
  });

  // ---------------------------------------------------------------------------
  // Archive projet (publique, servie par le panneau — identique à app.ts)
  // ---------------------------------------------------------------------------
  app.get("/nebula-bot-latest.zip", (_req, res) => {
    const zipPath = path.join(process.cwd(), "nebula-bot-latest.zip");
    if (!fs.existsSync(zipPath)) {
      return res.status(404).json({ error: "Project archive not available on this deployment." });
    }
    res.download(zipPath, "nebula-bot-latest.zip");
  });

  // ---------------------------------------------------------------------------
  // Proxy multi-bots
  // ---------------------------------------------------------------------------
  function resolveBotId(req: Request): string | null {
    const fromQuery = Array.isArray(req.query.bot) ? String(req.query.bot[0]) : req.query.bot;
    const raw = (typeof fromQuery === "string" && fromQuery.trim()) || req.get("x-nebula-bot")?.trim() || "";
    if (!raw) return supervisor.getDefaultBotId();
    if (!supervisor.hasBot(raw)) return null;
    return raw;
  }

  const proxyHandler = async (req: Request, res: Response) => {
    const botId = resolveBotId(req);
    if (!botId) {
      res.status(404).json({ error: `Bot inconnu : « ${String(req.query.bot || req.get("x-nebula-bot"))} »` });
      return;
    }
    await supervisor.proxyRequest(botId, req, res);
  };

  // Routes par-bot authentifiées → moteur enfant correspondant.
  app.all("/api/bot/*", proxyHandler);
  app.all("/api/bot", proxyHandler);
  app.all("/api/gemini/*", proxyHandler);
  app.all("/api/batch-downloads", proxyHandler);
  app.all("/api/batch-downloads/*", proxyHandler);
  app.all("/api/batch-downloads-stats", proxyHandler);

  // Liens médias publics (sans auth) → sondage des moteurs par jeton.
  // Rate limit dédié à bucket partagé (audit 8.76 / SEC-03) : ces routes ne
  // sont couvertes par le limiteur général (/api) que partiellement (/d/*
  // y échappe) et chaque jeton inconnu coûte une requête par moteur lancé.
  const mediaLimiter = rateLimit(120, 60_000, "media");
  app.get("/api/media/download/*", mediaLimiter, async (req, res) => {
    await supervisor.proxyMediaProbe(req, res);
  });
  app.get("/d/*", mediaLimiter, async (req, res) => {
    await supervisor.proxyMediaProbe(req, res);
  });

  return app;
}
